/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    procedures: Procedure;
    'legal-posts': LegalPost;
    quizzes: Quiz;
    categories: Category;
    theories: Theory;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    procedures: ProceduresSelect<false> | ProceduresSelect<true>;
    'legal-posts': LegalPostsSelect<false> | LegalPostsSelect<true>;
    quizzes: QuizzesSelect<false> | QuizzesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    theories: TheoriesSelect<false> | TheoriesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "procedures".
 */
export interface Procedure {
  id: number;
  title: string;
  slug?: string | null;
  subtitle?: string | null;
  zdjecie?: (number | null) | Media;
  content: (
    | {
        title: string;
        font?: boolean | null;
        content: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'Header';
      }
    | {
        title: string;
        attachments?:
          | {
              fileName: string;
              file?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'Attachments';
      }
    | {
        images?:
          | {
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ImagesSlider';
      }
    | {
        post: number | Quiz;
        id?: string | null;
        blockName?: string | null;
        blockType: 'QuizEncouragment';
      }
    | {
        title: string;
        references?:
          | {
              reference?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'References';
      }
    | {
        title?: string | null;
        realtedPosts?:
          | {
              procedure?: (number | null) | Procedure;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'RelatedPosts';
      }
    | {
        tabs: {
          title: string;
          content: (
            | {
                title: string;
                font?: boolean | null;
                content: string;
                id?: string | null;
                blockName?: string | null;
                blockType: 'Header';
              }
            | {
                title: string;
                attachments?:
                  | {
                      fileName: string;
                      file?: (number | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'Attachments';
              }
            | {
                images?:
                  | {
                      image?: (number | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'ImagesSlider';
              }
            | {
                title?: string | null;
                content: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                highlighted?: boolean | null;
                title2?: string | null;
                content2: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                highlighted2?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'TwoColumnsWithTtitles';
              }
          )[];
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'Tabs';
      }
    | {
        tabs: {
          title: string;
          icon?: (number | null) | Media;
          content: (
            | {
                title: string;
                font?: boolean | null;
                content: string;
                id?: string | null;
                blockName?: string | null;
                blockType: 'Header';
              }
            | {
                title: string;
                attachments?:
                  | {
                      fileName: string;
                      file?: (number | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'Attachments';
              }
            | {
                images?:
                  | {
                      image?: (number | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'ImagesSlider';
              }
            | {
                title?: string | null;
                content: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                highlighted?: boolean | null;
                title2?: string | null;
                content2: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                highlighted2?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'TwoColumnsWithTtitles';
              }
          )[];
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'DropdownList';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'RichText';
      }
    | {
        title?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        highlighted?: boolean | null;
        title2?: string | null;
        content2: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        highlighted2?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'TwoColumnsWithTtitles';
      }
    | {
        title?: string | null;
        desc?: string | null;
        /**
         * Wybierz jedno lub więcej zdjęć z biblioteki mediów.
         */
        images?: (number | Media)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'MediaTab';
      }
    | {
        image?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ImageBlock';
      }
  )[];
  category?: (number | null) | Category;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes".
 */
export interface Quiz {
  id: number;
  title: string;
  slug?: string | null;
  category: number | Category;
  questions?:
    | {
        questionText: string;
        answers?:
          | {
              answerText: string;
              isCorrect?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug?: string | null;
  image?: (number | null) | Media;
  parent?: {
    relationTo: 'categories';
    value: number | Category;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-posts".
 */
export interface LegalPost {
  id: number;
  title: string;
  slug?: string | null;
  subtitle?: string | null;
  estimation?: string | null;
  zajawka?: string | null;
  zdjecie?: (number | null) | Media;
  content: (
    | {
        title: string;
        font?: boolean | null;
        content: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'Header';
      }
    | {
        title: string;
        attachments?:
          | {
              fileName: string;
              file?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'Attachments';
      }
    | {
        images?:
          | {
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ImagesSlider';
      }
    | {
        post: number | Quiz;
        id?: string | null;
        blockName?: string | null;
        blockType: 'QuizEncouragment';
      }
    | {
        title: string;
        references?:
          | {
              reference?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'References';
      }
    | {
        title?: string | null;
        realtedPosts?:
          | {
              procedure?: (number | null) | Procedure;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'RelatedPosts';
      }
    | {
        tabs: {
          title: string;
          content: (
            | {
                title: string;
                font?: boolean | null;
                content: string;
                id?: string | null;
                blockName?: string | null;
                blockType: 'Header';
              }
            | {
                title: string;
                attachments?:
                  | {
                      fileName: string;
                      file?: (number | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'Attachments';
              }
            | {
                images?:
                  | {
                      image?: (number | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'ImagesSlider';
              }
            | {
                title?: string | null;
                content: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                highlighted?: boolean | null;
                title2?: string | null;
                content2: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                highlighted2?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'TwoColumnsWithTtitles';
              }
          )[];
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'Tabs';
      }
    | {
        tabs: {
          title: string;
          icon?: (number | null) | Media;
          content: (
            | {
                title: string;
                font?: boolean | null;
                content: string;
                id?: string | null;
                blockName?: string | null;
                blockType: 'Header';
              }
            | {
                title: string;
                attachments?:
                  | {
                      fileName: string;
                      file?: (number | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'Attachments';
              }
            | {
                images?:
                  | {
                      image?: (number | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'ImagesSlider';
              }
            | {
                title?: string | null;
                content: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                highlighted?: boolean | null;
                title2?: string | null;
                content2: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                highlighted2?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'TwoColumnsWithTtitles';
              }
          )[];
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'DropdownList';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'RichText';
      }
    | {
        title?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        highlighted?: boolean | null;
        title2?: string | null;
        content2: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        highlighted2?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'TwoColumnsWithTtitles';
      }
    | {
        title?: string | null;
        desc?: string | null;
        /**
         * Wybierz jedno lub więcej zdjęć z biblioteki mediów.
         */
        images?: (number | Media)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'MediaTab';
      }
    | {
        image?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ImageBlock';
      }
  )[];
  category?: (number | null) | Category;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theories".
 */
export interface Theory {
  id: number;
  title: string;
  slug?: string | null;
  subtitle?: string | null;
  estimation?: string | null;
  zajawka?: string | null;
  zdjecie?: (number | null) | Media;
  content: (
    | {
        title: string;
        font?: boolean | null;
        content: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'Header';
      }
    | {
        title: string;
        attachments?:
          | {
              fileName: string;
              file?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'Attachments';
      }
    | {
        images?:
          | {
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ImagesSlider';
      }
    | {
        post: number | Quiz;
        id?: string | null;
        blockName?: string | null;
        blockType: 'QuizEncouragment';
      }
    | {
        title: string;
        references?:
          | {
              reference?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'References';
      }
    | {
        title?: string | null;
        realtedPosts?:
          | {
              procedure?: (number | null) | Procedure;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'RelatedPosts';
      }
    | {
        tabs: {
          title: string;
          content: (
            | {
                title: string;
                font?: boolean | null;
                content: string;
                id?: string | null;
                blockName?: string | null;
                blockType: 'Header';
              }
            | {
                title: string;
                attachments?:
                  | {
                      fileName: string;
                      file?: (number | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'Attachments';
              }
            | {
                images?:
                  | {
                      image?: (number | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'ImagesSlider';
              }
            | {
                title?: string | null;
                content: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                highlighted?: boolean | null;
                title2?: string | null;
                content2: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                highlighted2?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'TwoColumnsWithTtitles';
              }
          )[];
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'Tabs';
      }
    | {
        tabs: {
          title: string;
          icon?: (number | null) | Media;
          content: (
            | {
                title: string;
                font?: boolean | null;
                content: string;
                id?: string | null;
                blockName?: string | null;
                blockType: 'Header';
              }
            | {
                title: string;
                attachments?:
                  | {
                      fileName: string;
                      file?: (number | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'Attachments';
              }
            | {
                images?:
                  | {
                      image?: (number | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'ImagesSlider';
              }
            | {
                title?: string | null;
                content: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                highlighted?: boolean | null;
                title2?: string | null;
                content2: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                highlighted2?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'TwoColumnsWithTtitles';
              }
          )[];
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'DropdownList';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'RichText';
      }
    | {
        title?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        highlighted?: boolean | null;
        title2?: string | null;
        content2: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        highlighted2?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'TwoColumnsWithTtitles';
      }
    | {
        title?: string | null;
        desc?: string | null;
        /**
         * Wybierz jedno lub więcej zdjęć z biblioteki mediów.
         */
        images?: (number | Media)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'MediaTab';
      }
    | {
        image?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ImageBlock';
      }
  )[];
  category?: (number | null) | Category;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'procedures';
        value: number | Procedure;
      } | null)
    | ({
        relationTo: 'legal-posts';
        value: number | LegalPost;
      } | null)
    | ({
        relationTo: 'quizzes';
        value: number | Quiz;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'theories';
        value: number | Theory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "procedures_select".
 */
export interface ProceduresSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  zdjecie?: T;
  content?:
    | T
    | {
        Header?:
          | T
          | {
              title?: T;
              font?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        Attachments?:
          | T
          | {
              title?: T;
              attachments?:
                | T
                | {
                    fileName?: T;
                    file?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ImagesSlider?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        QuizEncouragment?:
          | T
          | {
              post?: T;
              id?: T;
              blockName?: T;
            };
        References?:
          | T
          | {
              title?: T;
              references?:
                | T
                | {
                    reference?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        RelatedPosts?:
          | T
          | {
              title?: T;
              realtedPosts?:
                | T
                | {
                    procedure?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        Tabs?:
          | T
          | {
              tabs?:
                | T
                | {
                    title?: T;
                    content?:
                      | T
                      | {
                          Header?:
                            | T
                            | {
                                title?: T;
                                font?: T;
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                          Attachments?:
                            | T
                            | {
                                title?: T;
                                attachments?:
                                  | T
                                  | {
                                      fileName?: T;
                                      file?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          ImagesSlider?:
                            | T
                            | {
                                images?:
                                  | T
                                  | {
                                      image?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          TwoColumnsWithTtitles?:
                            | T
                            | {
                                title?: T;
                                content?: T;
                                highlighted?: T;
                                title2?: T;
                                content2?: T;
                                highlighted2?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        DropdownList?:
          | T
          | {
              tabs?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    content?:
                      | T
                      | {
                          Header?:
                            | T
                            | {
                                title?: T;
                                font?: T;
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                          Attachments?:
                            | T
                            | {
                                title?: T;
                                attachments?:
                                  | T
                                  | {
                                      fileName?: T;
                                      file?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          ImagesSlider?:
                            | T
                            | {
                                images?:
                                  | T
                                  | {
                                      image?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          TwoColumnsWithTtitles?:
                            | T
                            | {
                                title?: T;
                                content?: T;
                                highlighted?: T;
                                title2?: T;
                                content2?: T;
                                highlighted2?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        RichText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        TwoColumnsWithTtitles?:
          | T
          | {
              title?: T;
              content?: T;
              highlighted?: T;
              title2?: T;
              content2?: T;
              highlighted2?: T;
              id?: T;
              blockName?: T;
            };
        MediaTab?:
          | T
          | {
              title?: T;
              desc?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        ImageBlock?:
          | T
          | {
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  category?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-posts_select".
 */
export interface LegalPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  estimation?: T;
  zajawka?: T;
  zdjecie?: T;
  content?:
    | T
    | {
        Header?:
          | T
          | {
              title?: T;
              font?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        Attachments?:
          | T
          | {
              title?: T;
              attachments?:
                | T
                | {
                    fileName?: T;
                    file?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ImagesSlider?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        QuizEncouragment?:
          | T
          | {
              post?: T;
              id?: T;
              blockName?: T;
            };
        References?:
          | T
          | {
              title?: T;
              references?:
                | T
                | {
                    reference?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        RelatedPosts?:
          | T
          | {
              title?: T;
              realtedPosts?:
                | T
                | {
                    procedure?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        Tabs?:
          | T
          | {
              tabs?:
                | T
                | {
                    title?: T;
                    content?:
                      | T
                      | {
                          Header?:
                            | T
                            | {
                                title?: T;
                                font?: T;
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                          Attachments?:
                            | T
                            | {
                                title?: T;
                                attachments?:
                                  | T
                                  | {
                                      fileName?: T;
                                      file?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          ImagesSlider?:
                            | T
                            | {
                                images?:
                                  | T
                                  | {
                                      image?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          TwoColumnsWithTtitles?:
                            | T
                            | {
                                title?: T;
                                content?: T;
                                highlighted?: T;
                                title2?: T;
                                content2?: T;
                                highlighted2?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        DropdownList?:
          | T
          | {
              tabs?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    content?:
                      | T
                      | {
                          Header?:
                            | T
                            | {
                                title?: T;
                                font?: T;
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                          Attachments?:
                            | T
                            | {
                                title?: T;
                                attachments?:
                                  | T
                                  | {
                                      fileName?: T;
                                      file?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          ImagesSlider?:
                            | T
                            | {
                                images?:
                                  | T
                                  | {
                                      image?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          TwoColumnsWithTtitles?:
                            | T
                            | {
                                title?: T;
                                content?: T;
                                highlighted?: T;
                                title2?: T;
                                content2?: T;
                                highlighted2?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        RichText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        TwoColumnsWithTtitles?:
          | T
          | {
              title?: T;
              content?: T;
              highlighted?: T;
              title2?: T;
              content2?: T;
              highlighted2?: T;
              id?: T;
              blockName?: T;
            };
        MediaTab?:
          | T
          | {
              title?: T;
              desc?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        ImageBlock?:
          | T
          | {
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  category?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes_select".
 */
export interface QuizzesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  questions?:
    | T
    | {
        questionText?: T;
        answers?:
          | T
          | {
              answerText?: T;
              isCorrect?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theories_select".
 */
export interface TheoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  estimation?: T;
  zajawka?: T;
  zdjecie?: T;
  content?:
    | T
    | {
        Header?:
          | T
          | {
              title?: T;
              font?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        Attachments?:
          | T
          | {
              title?: T;
              attachments?:
                | T
                | {
                    fileName?: T;
                    file?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ImagesSlider?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        QuizEncouragment?:
          | T
          | {
              post?: T;
              id?: T;
              blockName?: T;
            };
        References?:
          | T
          | {
              title?: T;
              references?:
                | T
                | {
                    reference?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        RelatedPosts?:
          | T
          | {
              title?: T;
              realtedPosts?:
                | T
                | {
                    procedure?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        Tabs?:
          | T
          | {
              tabs?:
                | T
                | {
                    title?: T;
                    content?:
                      | T
                      | {
                          Header?:
                            | T
                            | {
                                title?: T;
                                font?: T;
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                          Attachments?:
                            | T
                            | {
                                title?: T;
                                attachments?:
                                  | T
                                  | {
                                      fileName?: T;
                                      file?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          ImagesSlider?:
                            | T
                            | {
                                images?:
                                  | T
                                  | {
                                      image?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          TwoColumnsWithTtitles?:
                            | T
                            | {
                                title?: T;
                                content?: T;
                                highlighted?: T;
                                title2?: T;
                                content2?: T;
                                highlighted2?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        DropdownList?:
          | T
          | {
              tabs?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    content?:
                      | T
                      | {
                          Header?:
                            | T
                            | {
                                title?: T;
                                font?: T;
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                          Attachments?:
                            | T
                            | {
                                title?: T;
                                attachments?:
                                  | T
                                  | {
                                      fileName?: T;
                                      file?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          ImagesSlider?:
                            | T
                            | {
                                images?:
                                  | T
                                  | {
                                      image?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          TwoColumnsWithTtitles?:
                            | T
                            | {
                                title?: T;
                                content?: T;
                                highlighted?: T;
                                title2?: T;
                                content2?: T;
                                highlighted2?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        RichText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        TwoColumnsWithTtitles?:
          | T
          | {
              title?: T;
              content?: T;
              highlighted?: T;
              title2?: T;
              content2?: T;
              highlighted2?: T;
              id?: T;
              blockName?: T;
            };
        MediaTab?:
          | T
          | {
              title?: T;
              desc?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        ImageBlock?:
          | T
          | {
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  category?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  email: string;
  phone?: string | null;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}